name: hyp3-ci
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python
  - pip
  # For packaging, and testing
  - flake8
  - flake8-import-order
  - flake8-blind-except
  - flake8-builtins
  - setuptools
  - setuptools_scm
  - wheel
  - pytest
  - pytest-console-scripts
  - pytest-cov
  # For running
  - hyp3lib>=3,<4
  - importlib_metadata
